### ISSUE TITLE
Need a `luar.null` value

### ISSUE THREAD

**Issue by stevedonovan** [stevedonovan/luar#11]
Slices and Maps may contain `nil` values, but corresponding Lua tables cannot. So luar should use a unique placeholder and ensure that it is available to Lua as `luar.null`. This isn't a problem with proxies (which mostly behave like their Go counterparts) but when copying slices and maps to Lua tables.

**Comment by Ambrevar** [comment]
Not sure why this hasn't been closed... Please re-open if this is still an issue.
