### ISSUE TITLE
bad import "unsafe" 

### ISSUE THREAD

**Issue by ookpalm** [stevedonovan/luar#16]
I tried to run luar on an Go - Appengine project. However I encountered 

"o-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/stevedonovan/luar/luar.go"

I searched and found that the package is trimmed on GAE. Does this mean I cannot use luar with golua on GAE?

Thank you.

**Comment by Ambrevar** [comment]
Also see https://github.com/layeh/gopher-luar.
I've removed the 'unsafe' import in https://github.com/stevedonovan/luar/commit/63246cf9b270904e56720123a986065e63141ae6.
