### ISSUE TITLE
proxyMap race

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [stevedonovan/luar#21]
The:
`var proxyMap = map[*valueProxy]reflect.Value{}`
is used unprotected, so multiple concurrent Lua environments can corrupt it. I have submitted pull-request for that, but the ultimate solution is to Unite `lua.State` and `proxyMap` for that state in `luar.State` object, and passing around that object. Unfortunately functions like `map__pairs`, and `slice__ipairs`, doesn't make this straight forward to make. Since you are more familiar with the library, can you make the needed refactoring. Thank you for the wonderful project.

**Comment by Ambrevar** [comment]
I don't think there is an easy way to create a `Luar.State` since the metatable functions require a `lua.State` parameter.
Correct me if I'm wrong and re-open the issue.
