### ISSUE TITLE
luajit

### ISSUE THREAD

**Issue by glycerine** [stevedonovan/luar#23]
Is luajit supported/workable with luar, or only lua?

Thanks!

Jason

**Comment by stevedonovan** [comment]
LuaJit is 5.1 compatible so it should work, would have to adjust the shared
library of course. I'll have a look when I get back from my travels.

**Comment by rabarar** [comment]
Is luajit supported? I was having issues and would like to know the official word.

**Comment by stevedonovan** [comment]
It _should_ work, because LuaJIT is 5.1 binary compatible; let me actually
try this. Any particular issues?

**Comment by rabarar** [comment]
I think the problem was around the ffi library

local ffi = require("ffi") ffi.cdef[[ int printf(const char *fmt, ...); ]] ffi.C.printf("Hello %s!", "world")
The script above failed for me...

**Comment by rabarar** [comment]
Steve,

Just checking on the email reply -- making sure you got it..

By the way, I've thoroughly enjoyed reading your code -- you're GoToLua function creation is very cool.

Rob

**Comment by stevedonovan** [comment]
Sure, I'm here - will have a bit of time to look at this issue over the
weekend.

Not sure how LuaJIT as a _shared library_ resolves its ffi symbols....

**Comment by stevedonovan** [comment]
Actually works fine - there is a subtety with `printf` here:

```lua
examples$ ./luar
luar 1.2 Copyright (C) 2013-2014 Steve Donovan
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> ffi = require 'ffi'
> ffi.cdef [[ int printf(const char *fmt, ...); ]]
> ffi.C.printf("hi %f %s\n",10,'hello')
hi 10.000000 hello
```

In a varargs case, _any_ number is passed as a double - so you get odd stuff when you use %d.

**Comment by tolbrino** [comment]
Just fyi, I've used luar with luajit for some time without issues.

**Comment by glycerine** [comment]
Yep, Luar works fine with LuaJIT. As Steve says, LuaJIT is 5.1 binary compatible.

**Comment by glycerine** [comment]
Hmm... There's a massive slowdown that happens when running LuaJIT with Luar installed. I'm seeing about a 10x slowdown.  Going to re-open this issue.

@stevedonovan @aarzilli Do you have any idea why Luar would be slowing down LuaJIT so much?  I suspect the replacing the ipairs and pairs may have something to do with it, but I have not had a chance to look into it. I see the comment in the code below about a performance issue from the past.

https://github.com/stevedonovan/luar/blob/master/luar.go#L168
~~~
    Register(L, "", Map{
        "pairs": ProxyPairs,
        "type":  ProxyType,
    })
    // 'ipairs' needs a special case for performance reasons.
    RegProxyIpairs(L, "", "ipairs")
~~~

**Comment by glycerine** [comment]
No change when I comment out the pairs and ipairs, but I get a massive return of speed, back to usual LuaJIT perf, when I comment out the ProxyType override.
~~~
    Register(L, "", Map{
        "pairs": ProxyPairs,
        "type":  ProxyType,  // <<< looks like this is the culprit.
    })
    // 'ipairs' needs a special case for performance reasons.
    RegProxyIpairs(L, "", "ipairs")
~~~

**Comment by glycerine** [comment]
Can the "type()" override with ProxyType() be safely omitted perhaps, or is it essential?

**Comment by Ambrevar** [comment]
Can you provide examples and benchmarks of code where you experience a slow-down?

`ProxyType` enhances the original `type`.  From the documentation:
```
It behaves like Lua's "type" except for proxies for which it returns
'table<TYPE>', 'string<TYPE>' or 'number<TYPE>' with TYPE being the go type.
```

It is optional and you can easily turn it off during the initialization of Luar.

**Comment by glycerine** [comment]
> It is optional and you can easily turn it off during the initialization of Luar.

but will Luar break with it off?  I haven't experienced any breaks, but then again, I haven't tried everything.  Does Luar reflect-based translation depend upon getting the ProxyType back correctly, is the real question.

I observed the massive slowdown on my matrix multiplication test:
https://github.com/gijit/gi/blob/master/pkg/compiler/mat_test.go#L70

addendum: I realize that's not a micro benchmark like you were probably hoping for. It just does alot of type() checking, again and again, while reading and writing matrix entries.

**Comment by Ambrevar** [comment]
`ProxyType` is a purely cosmetic enhancement, it won't break anything when it's off.

**Comment by glycerine** [comment]
> ProxyType is a purely cosmetic enhancement, it won't break anything when it's off.

Awesome. Thank you @Ambrevar.

**Comment by Ambrevar** [comment]
Regarding your example, can you provide something more minimal and dependency-free?

**Comment by glycerine** [comment]
> Regarding your example, can you provide something more minimal and dependency-free?

No. Not easily. Just make a bunch of type() calls in a loop. that should do it.

**Comment by Ambrevar** [comment]
But your example does not contain any call to `type`, does it?
I don't see anything in Luar's codebase that would slow down the execution if `type` isn't called on the Lua side.

**Comment by glycerine** [comment]
>But your example does not contain any call to type, does it?

It does, its just hidden under many many layers. 

I'm just calling type() alot, so paying for the C->go transition cost every time magnifies the contrast with just staying in C land with the native type().

**Comment by Ambrevar** [comment]
Alright, then I guess you got your answer here.

Keep in mind that Luar is here for convenience only: anything it does
induces a performance cost.  Don't use Luar in tight loops, stick to
Golua instead.

**Comment by glycerine** [comment]
I suppose a cache on the C side could help considerably. But that would be future feature work, and deserves its own ticket. I'll close this out. Thanks everyone for the help and input.
