### ISSUE TITLE
Support cycle detection

### ISSUE THREAD

**Issue by Ambrevar** [stevedonovan/luar#27]
In Go, a cycle within a linked list will yield an infinite loop when converted to Lua.
In Lua, a table containing a cycle will yield an infinite loop when converted to Go.

Can we perform cycle detection one way or another?

**Comment by stevedonovan** [comment]
The short answer is yes, but it might be a bit expensive. The usual solution is to keep a map of visited objects and traverse the object, stopping at an already-visited object.

**Comment by Ambrevar** [comment]
After a first attempt at detecting cycles in LuaToGo, I measured a ~20% slowdown. Considering that Luar is focusing on ease of use before performance, this could be considered acceptable.
I'll push a branch when I'll be done the other way and request for comments.

**Comment by Ambrevar** [comment]
I've just pushed a `cycle-detenction` branch.

It has 2 commits: the second one optimizes the code for scalars (strings, numbers, etc.) at the expense of references (tables).
It only affects LuaToGo. GoToLua is optimized for scalars in both commits.

Some benchmarks:

* master

		BenchmarkLuaToGoSliceInt-2           	   10000	    190502 ns/op
		BenchmarkLuaToGoSliceMap-2           	    3000	    488444 ns/op
		BenchmarkLuaToGoSliceMapUnique-2     	    3000	    482154 ns/op
		BenchmarkLuaToGoMapInt-2             	    5000	    357783 ns/op
		BenchmarkLuaToGoMapSlice-2           	    2000	    678075 ns/op
		BenchmarkLuaToGoMapSliceUnique-2     	    2000	    686621 ns/op

		BenchmarkGoToLuaSliceInt-2           	   10000	    136314 ns/op
		BenchmarkGoToLuaSliceSlice-2         	    5000	    326460 ns/op
		BenchmarkGoToLuaSliceSliceUnique-2   	    5000	    314216 ns/op
		BenchmarkGoToLuaMapInt-2             	   10000	    179803 ns/op
		BenchmarkGoToLuaMapSlice-2           	    5000	    368634 ns/op
		BenchmarkGoToLuaMapSliceUnique-2     	    5000	    367000 ns/op

* cycle-detection (optimized for references)

		BenchmarkLuaToGoSliceInt-2           	    5000	    235789 ns/op
		BenchmarkLuaToGoSliceMap-2           	   10000	    149007 ns/op *
		BenchmarkLuaToGoSliceMapUnique-2     	    2000	    655665 ns/op
		BenchmarkLuaToGoMapInt-2             	    3000	    445911 ns/op
		BenchmarkLuaToGoMapSlice-2           	    5000	    355718 ns/op *
		BenchmarkLuaToGoMapSliceUnique-2     	    2000	    900332 ns/op

		BenchmarkGoToLuaSliceInt-2           	   10000	    143007 ns/op
		BenchmarkGoToLuaSliceSlice-2         	    5000	    273768 ns/op
		BenchmarkGoToLuaSliceSliceUnique-2   	    2000	    668399 ns/op
		BenchmarkGoToLuaMapInt-2             	   10000	    182345 ns/op
		BenchmarkGoToLuaMapSlice-2           	    5000	    325700 ns/op
		BenchmarkGoToLuaMapSliceUnique-2     	    2000	    771846 ns/op

* cycle-detection (optimized for scalars)

		BenchmarkLuaToGoSliceInt-2           	   10000	    194986 ns/op
		BenchmarkLuaToGoSliceMap-2           	   10000	    234278 ns/op *
		BenchmarkLuaToGoSliceMapUnique-2     	    2000	    604552 ns/op
		BenchmarkLuaToGoMapInt-2             	    5000	    350189 ns/op
		BenchmarkLuaToGoMapSlice-2           	    3000	    400227 ns/op *
		BenchmarkLuaToGoMapSliceUnique-2     	    2000	    810880 ns/op

		BenchmarkGoToLuaSliceInt-2           	   10000	    143233 ns/op
		BenchmarkGoToLuaSliceSlice-2         	    5000	    276706 ns/op
		BenchmarkGoToLuaSliceSliceUnique-2   	    2000	    687696 ns/op
		BenchmarkGoToLuaMapInt-2             	   10000	    182369 ns/op
		BenchmarkGoToLuaMapSlice-2           	    5000	    324901 ns/op
		BenchmarkGoToLuaMapSliceUnique-2     	    2000	    750818 ns/op

The benchmarks are not all frequent real-life use-cases:

- `*Int`: A table of integers.
- `*Unique`: A table containing other tables.
- `*Map` and `*Slice`: a map / slice only containing references to itself.

In the benchmarks marked with a `*`, reference optimized code does better.
Nonetheless, the `*Int` and `*Unique` are non-cyclic and, I suppose, far more
frequent cases than the cyclic structures. Which is why I'd argue for the scalar
optimization.

Compared to master, the new branch with scalar optimization is
- faster for cyclic structure;
- as fast for tables of scalars;
- 10%-25% slower for tables of tables.

**Comment by stevedonovan** [comment]
That's excellent, sir! Definitely a price worth paying for non-panicking code...

**Comment by Ambrevar** [comment]
Merged.
