### ISSUE TITLE
Better proxy__tostring

### ISSUE THREAD

**Issue by Ambrevar** [stevedonovan/luar#28]
Instead of type, print stringer value.

``` go
- L.PushString(obj.Type().String())
+ L.PushString(fmt.Sprintf("%v", obj))
```

See https://github.com/bitwalker/luar/commit/5d52c02e476f9f766bf027e86b5033ba30018941

This seems better. Question is: why did we print the type in the first place?

**Comment by stevedonovan** [comment]
Good question. This does seem a better solution, unless people are expecting a certain behaviour here.

**Comment by Ambrevar** [comment]
I think the stringer value is the expected behaviour. I'll merge this just now.
