### ISSUE TITLE
Extend __type metamethod for proxies

### ISSUE THREAD

**Issue by Ambrevar** [stevedonovan/luar#29]
See: https://github.com/bitwalker/luar/commit/9747fcd0e1bcc9fbb24e6221f5577b2fbf31b3ad
This allows for `type()` to return something more interesting about proxies.
The aforementioned commit returns `table`. I like the idea of making the distinction between real Lua tables and proxy tables. What about returning
- `userdata(map)`
- `proxy(map)`.
- `goluadata(map)`.
- `luardata(map)`.

Comments?

**Comment by stevedonovan** [comment]
I would agree that the distinction may be useful.  I wonder what the _original intention_ here is - that the patch is to ensure that Lua code does consider proxies to be tables?

**Comment by Ambrevar** [comment]
Second thoughts...

- Part of the type description should contain the word "table" so that it is possible to type-check any kind of tables, proxy or not. It is easier if we keep the word at the beginning so we can subscript & compare.

- Use something other than parentheses, e.g. angle bracket, to avoid confusion with function call syntax.

- No need to mention "userdata" since it is implied.

Further questions:

- Should we prefix with an implementation name? `table<go/map>` or `table<map>`?
- If prefixed, what shall it be? `table<go/map>`, `table<luar/map>`?
- If prefixed, what separator shall we use? `table<go.map>`, `table<luar/map>`?

I would go for simplicity and opt for `table<map>`.

**Comment by stevedonovan** [comment]
Simplicity feels like a good thing here. Either it's a proxy or it's already a Lua table.

**Comment by Ambrevar** [comment]
To point of having a prefix is for Lua program to make the distinction between their host platforms (original Lua, luajit, luar, golua, etc.). Not sure there is any convention there, and not sure that would ever be needed either.

**Comment by stevedonovan** [comment]
Such scripts can query their own environment,`_VERSION` etc.

**Comment by Ambrevar** [comment]
But both golua and luar keep `_VERSION` unchanged. Which is probably the right thing to do...
Any thought on that?

**Comment by Ambrevar** [comment]
Changing the `type` function will break backward compatibility though, so I suggest to move this together with the API change #32.

**Comment by Ambrevar** [comment]
I've pushed the changes to the `proxytype` branch. Let's wait for what will get decided regarding the API change.

**Comment by Ambrevar** [comment]
The change has been merged in the v2 branch.
