### ISSUE TITLE
On the usefulness of 't', the type argument in GoToLua

### ISSUE THREAD

**Issue by Ambrevar** [stevedonovan/luar#31]
I've been working on simplifying the GoToLua function which I've always found much too complex for what it does.
It turns out that the test suite passes when I set `t = val.Type()` at the beginning. In other words, none of the tests force the type.

What was the original intention? What does "forcing the type" even mean? The type switch does not seem to force anything.

**Comment by stevedonovan** [comment]
Good point! The only thing crucial there is `dontproxify` I think.  `t` is set anyway, AFAIK

**Comment by Ambrevar** [comment]
Well, the original algorithm is a bit intricate, and at first glance it is not clear that `t` will always be derived from `val`. After a closer look, it turns out that it *does not*, but then it is a bug or results in a panic.

**Comment by stevedonovan** [comment]
The first rule is _don't panic_. Douglas Adams' Hitchhiker books were all about Go.

**Comment by Ambrevar** [comment]
I've pushed the change.
