### ISSUE TITLE
API change

### ISSUE THREAD

**Issue by Ambrevar** [stevedonovan/luar#32]
The `GoToLua` and `LuaToGo` functions are poorly designed:

``` go
func GoToLua(L *lua.State, t reflect.Type, val reflect.Value, dontproxify bool)
```
- `t` is useless.
- `val` should be an `interface{}`.
- `dontproxify` is confusing and not convenient. We should use different function names like `GoToLua` and `GoToLuaProxy`.

``` go
func LuaToGo(L *lua.State, t reflect.Type, idx int) interface{}
```

- `t` and `interface{}` force the use of reflection and type switching. We should store the result in the value pointed by the `interface{}` passed as argument, just like `json.Unmarshal`.

The new functions would be:

``` go
func GoToLua(L *lua.State, v interface{})

func GoToLuaProxy(L *lua.State, v interface{})

func LuaToGo(L *lua.State, v interface{}, idx int) error
```

This is an easy change but would break backward-compatibility.
This might not be such a big deal considering the low usage or Luar, but this is bad practice nonetheless.
Shall we move to a Luar2 repo?
Or shall we ignore this change?

**Comment by stevedonovan** [comment]
Go versioning of packages used to be a ... tricky business. But people keep their own forks when they want to isolate themselves from any changes.  Your proposal makes much more sense - de-emphasize reflection (which is an implementation detail here). I wonder if the old klunky API could be _deprecated_ but available against the new API for a while.

**Comment by Ambrevar** [comment]
As you suggest, we could opt for a transition period: Leave the deprecated functions for a while, then remove them. Then we need to new names. Not sure what can be as simple as GoToLua and LuaToGo...

**Comment by Ambrevar** [comment]
Other changes:

- Remove the Copy* functions as they are redundant with GoToLua and LuaToGo.
- Replace `map2table`, `slice2table` and `struct2table` with a single `luar.totable`.
- Remove `luar.type`?

**Comment by Ambrevar** [comment]
@stevedonovan What's your preference?
I think a transition period would add more complexity than solve problems. I'd rather leave a "Compatibility notice" in the readme.

Let's decide on something. My preferences, in order:
- Create a new repo
- Change directly on top of the current repo and leave a compatibility notice.
- No change at all
- Progressive changes.

**Comment by Ambrevar** [comment]
I've worked on the API rewrite: it was much more than I expected. I've discovered many more bugs and design issues in the process. The result has been pushed on branch `v2`. Here is the change log taken from the README:

## Change log

The main differences with the previous version:

- The function prototypes of `GoToLua` and `LuaToGo` are simpler and do not
require the use of reflection from the callers. The `dontproxify` argument is
gone, use `GoToLuaProxy` to control proxification.

- The `Copy*` functions and `GoLuaFunc` are gone, use `GoToLua` and `LuaToGo` instead.

- Use `Register` instead of `RawRegister`.

- `InitProxies` is gone since it was not needed.

- The `LuaObject` and `LuaTableIter` structure fields are unexported.

- LuaObject methods not only work on Lua functions but also on anything with a
`__call` metamethods. Idem for tables and the `__index`/`__newindex`
metamethods.

- Use `NewLuaObjectFromName(L, "_G")` instead of `Global`.

- `Lookup` and `Geti` gone. Instead the `Get` and `GetObject` functions are
variadic: each subfield argument can be any valid Lua key (string, integer...).

- Use `(*LuaObject) Call` instead of `(*LuaObject) Callf`. The protoype of
`(*LuaObject) Call` has changed in a fashion similar to `GoToLua` and `LuaToGo`.
`Types` is gone as it is no longer needed.

- Register `ProxyIpairs` and `ProxyPairs` instead of calling `LuarSetup`.

- Register and use `Unproxify` instead of `ArrayToTable`, `MapToTable`,
`ProxyRaw`, `SliceToTable` and `StructToTable`.

- `ComplexReal` and `ComplexImag` have been replaced by the proxy attributes
`real` and `imag`, respectively.

- `SliceSub` and `SliceAppend` have been replaced by the proxy methods
`slice` and `append`, respectively.
Slice proxies have the `cap` metamethod alongside `append` and `slice`.

- String proxies have a `slice` method just like slice proxies. They can be
looped rune-by-rune over with `ipairs`.

The range of supported conversion has been extended:

- LuaToGo can convert to interfaces and pointers with several levels of indirection.

- LuaToGo can convert to non-empty maps and structs.
