### ISSUE TITLE
Non-exported fields in struct proxies

### ISSUE THREAD

**Issue by Ambrevar** [stevedonovan/luar#33]
Luar allows for reading non-exported fields in struct proxies, but not for setting them (it will panic, that's Go's rule). I find this confusing and I think we should hide non-exported fields.

Any comment on that?

**Comment by stevedonovan** [comment]
Yeah, reflection allows us to do things we probably should not do.  I also feel that the public interface is what people should get.  The only question - same as with the API refactor - is how many people depend on this 'feature'.  But this is the correct way to go.

**Comment by Ambrevar** [comment]
I've pushed the change.
