### ISSUE TITLE
GoLuaFunc and RawRegister

### ISSUE THREAD

**Issue by Ambrevar** [stevedonovan/luar#36]
@stevedonovan What is the point of the separation Register / RawRegister? As far as I get it, RawRegister panics when the prototype is not Lua friendly, that's the only use I see.

Moreover, I'm wondering why GoLuaFunc isn't part of GoToLua: it would make the API simpler. Any good reason for that?

**Comment by stevedonovan** [comment]
Register takes 'arbitrary' Go functions and creates a reflection func for calling it directly.  This is convenient but obviously not so efficient. RawRegister gets passed Go functions which directly access the Lua API.  So it allows people to write Lua API functions _if_ performance is an issue.

It would be simpler for GoLuaFunc/GoToLua to be the same, but there's no harm in keeping the separation (the "ain't broke don't fix" principle)

**Comment by Ambrevar** [comment]
From `register()`:

``` go
			if convertFun {
				L.PushGoFunction(GoLuaFunc(L, val))
			} else {
				lf := val.(func(*lua.State) int)
				L.PushGoFunction(lf)
			}
```

and

``` go
func GoLuaFunc(L *lua.State, fun interface{}) lua.LuaGoFunction {
	switch f := fun.(type) {
	case func(*lua.State) int:
		return f
```

So if we remove the distinction between `Register` and `RawRegister`, we remove the `if convertFun` branching while the formerly raw-registered functions go through a new switch branch in GoLuaFunc.

Summary:
- Raw-registered functions have the same cyclomatic complexity.
- Regular registered functions have one less branch.
- Both have one less function call.

> but there's no harm

The harm is in making the API more complex. I'd like to remove GoLuaFunc as part of the API change #32.

**Comment by Ambrevar** [comment]
Fixed in https://github.com/stevedonovan/luar/commit/9206b6933fef545a2a8357c878ac285ad5e8d478.
