### ISSUE TITLE
Could move ProxyIpairs to luar table?

### ISSUE THREAD

**Issue by huangwei1024** [stevedonovan/luar#42]
`ProxyIpairs`, `ProxyPairs` replace Lua original `ipairs` and `pairs` functions, it impact on performance so much. `pairs` and `ipairs` be invoked in Lua on high frequence.
so, `ProxyIpairs`, `ProxyPairs` move to `luar` table may be better?

**Comment by stevedonovan** [comment]
This seems important. @Ambrevar , how does this fit with the new API?

**Comment by Ambrevar** [comment]
One of the main features of the v2 API is that it lets you initialize Luar manually: the force `Init` of v1 was one of the main reasons for the many forks it generated.

If you don't want to replace `pairs` and `ipairs`, simply initialize as follow:

func MyInit() *lua.State {
	var L = lua.NewState()
	L.OpenLibs()
	luar.Register(L, "luar", luar.Map{
		// Functions.
		"unproxify": luar.Unproxify,

		"method": luar.ProxyMethod,

		"chan":    luar.MakeChan,
		"complex": luar.Complex,
		"map":     luar.MakeMap,
		"slice":   luar.MakeSlice,

		// Values.
		"null": luar.Null,
	})
	luar.Register(L, "", luar.Map{
		// "ipairs": luar.ProxyIpairs,
		// "pairs":  luar.ProxyPairs,
		"type":   luar.ProxyType,
	})
	return L
}

As for the performance issue: the `ProxyPairs` and `ProxyIpairs` function are rather minimal, in fact there are almost copy-paste from Lua's official implementation.

```
func ProxyPairs(L *lua.State) int {
	// See Lua >=5.2 source code.
	if L.GetMetaField(1, "__pairs") {
		L.PushValue(1)
		L.Call(1, 3)
		return 3
	}

	L.CheckType(1, lua.LUA_TTABLE)
	L.PushGoFunction(pairsAux)
	L.PushValue(1)
	L.PushNil()
	return 3
}
```

I don't think we can make this any faster, while it remains a prime requirement for Luar's goal of convenience-of-use.

**Comment by huangwei1024** [comment]
I modified that in my project. but I think it is not good idea to interact between Go and Lua, too heavy. Bind but not Override.

I just want luar bind some Go libraries to Lua, when Lua need use it. but now there can not get rid of the Go bind everywhere. In this case, no convenience, only boring.
Like `toluapp` bind C++ and Lua, you can see he put `type` at `tolua` table.

Besides, `ProxyPairs` and `ProxyIpairs` could be endure, because it be invoke only once in one for-loop, but there put `pairsAux` and `ipairsAux`, just for simulate Lua `next`, it's hotspot!

```
local t = {
	[1] = 1,
	[2] = 2,
	a = "a",
	b = "b",
	c = "c",
	d = "d",
	[4] = 4,
}
for i = 100, 200 do
	t[i] = i
end

local pairs = pairs
local luar_pairs = luar.pairs
print("pairs", pairs, "luar_pairs", luar_pairs)

function pairs_test()
	local tmp
	for i = 1, 1000 do
		for k, v in pairs(t) do
			tmp = v
		end
	end
end

function luar_pairs_test()
	local tmp
	for i = 1, 1000 do
		for k, v in luar_pairs(t) do
			tmp = v
		end
	end
end
```

under go version go1.7.3 windows/amd64.
use lua:
> pairs   function: 000000000073FD80      luar_pairs      userdata: 00000000007403E8
Benchmark_LuaPairs-8
     300           5120650 ns/op
Benchmark_LuarPairs-8
      10         140717860 ns/op
PASS
ok      command-line-arguments  3.662s

use luajit:
> pairs   function: builtin#5     luar_pairs      userdata: 0x02138df8
Benchmark_LuaPairs-8
    2000            638080 ns/op
Benchmark_LuarPairs-8
      10         131416700 ns/op
PASS
ok      command-line-arguments  2.894s

and it no good for JIT. calls to C functions via the classic C API will never be inlined in JIT-compiled code.

**Comment by Ambrevar** [comment]
I am having a hard time to understand what you mean.

>  but now there can not get rid of the Go bind everywhere.

Wrong, you can select exactly what you want from Luar. If you don't use `Init()`, Luar will do nothing.

Luar main goal is convenience. Performance is only second.
If you have a tight loop, don't use Luar functions, rely on Golua instead.

What is your issue? What do you want fixed? What do you suggest?

**Comment by huangwei1024** [comment]
If dont use `Init()`, how can I use `chan` in Lua? I just want `luar` appeared when I needed.

I suggest dont replace Lua original function or move them to `luar` table. it can got both convenience and performance. why not do that?
If all Lua original function be replaced by `Luar`, why not use [go-lua](https://github.com/Shopify/go-lua), its more convenience.

**Comment by Ambrevar** [comment]
The `Init()` function is `MyInit()` function minus the comments. You do not have to use it to use Luar!
Have you tried `MyInit()`?
Again, Luar does not force you to replace any function.

**Comment by Ambrevar** [comment]
I've benchmarked the following change:
```
func ProxyPairs(L *lua.State) int {
	// See Lua >=5.2 source code.
	if L.GetMetaField(1, "__pairs") {
		L.PushValue(1)
		L.Call(1, 3)
		return 3
	}

	L.CheckType(1, lua.LUA_TTABLE)
-	L.PushGoFunction(pairsAux)
+	L.GetGlobal("next")
	L.PushValue(1)
	L.PushNil()
	return 3
}
```
Result:
```
pairs	function: 0x8fc4a0	luar_pairs	userdata: 0x903758
BenchmarkPairs-2       	pairs	function: 0x8fd120	luar_pairs	userdata: 0x8fef18
     100	  11431969 ns/op
pairs	function: 0x8ffc80	luar_pairs	userdata: 0x900c28
BenchmarkLuarPairs-2   	pairs	function: 0x903560	luar_pairs	userdata: 0x902738
     100	  14162616 ns/op
PASS
```

It gives a huge performance boost indeed since it saves many cgo calls.
I'll commit the change.

Any idea how to do it for `ipairs`?
One way would be to save a reference to Lua's `ipairs` and call it in `ProxyIpairs` instead of `ipairsAux`.

**Comment by huangwei1024** [comment]
rename Lua's `ipairs` to other name, just like `luaSetupCode` did in old version.
In my opinion, place a Lua file in repo, and load it in `Init` is good glue. but it not a pure Go implementation, may be breaking your goal.

**Comment by Ambrevar** [comment]
That's not the point. Point is, Luar must be usable without calling `Init()`. The Lua state `L` is not bound to any state (i.e. global variable) and thus cannot be parameterized such as saving a reference to `ipairs`.

Example: if the user decides to override `ipairs` first and only then to call `Init()` there is no way to gain access to the original `ipairs`. There is also no way to make the distinction between different `ipairs`.

Unless someone can think of a neat trick, I'm afraid `ProxyIpairs` will have to remain very slow.

**Comment by huangwei1024** [comment]
> if the user decides to override ipairs first
I think in `Init` save user's `ipairs` no problem in common practice.
In my work, I also override `ipairs`  in Lua.
like,
```
functione CList:__ipairs()
  return lua_ipairs(self.data)
end

local lua_ipairs = ipairs
function ipairs(t)
     if t.__class then
        return t.__ipairs(t)
    end
    return lua_ipairs(t)
end
```
if you got real Lua original `lua_ipairs`, `ProxyIpairs` will bypass `CList:__ipairs`, it will miss some user's custom handle. 

if user override `ipairs` first, the caller sequence was `ProxyIpairs` -> user `ipairs` -> `lua_ipairs`, it's ok.
if `Init` first and then user override, caller sequence was user `ipairs` -> `ProxyIpairs` -> `lua_ipairs`

**Comment by Ambrevar** [comment]
What you say is right, unless the user overrides `ipairs` with `ProxyIpairs`: calling `ipairs` would yield an infinite recursion. This is the main problem.

The only way around this, I believe, is to keep a Lua reference to ipairs. The question is, how do we make this reference abailable _in all cases_?

**Comment by Ambrevar** [comment]
Alright, I found a way to fix performance using the default case (i.e. calling `Init()`) while retaining backward compatibility.

```
// Register a function 'table.name' equivalent to ProxyIpairs that uses 'ipairs'
// when '__ipairs' is not present.
//
// This is much faster than ProxyIpairs.
func RegProxyIpairs(L *lua.State, table, name string) {
	L.GetGlobal("ipairs")
	ref := L.Ref(lua.LUA_REGISTRYINDEX)

	f := func(L *lua.State) int {
		// See Lua >=5.2 source code.
		if L.GetMetaField(1, "__ipairs") {
			L.PushValue(1)
			L.Call(1, 3)
			return 3
		}
		L.RawGeti(lua.LUA_REGISTRYINDEX, ref)
		L.PushValue(1)
		L.Call(1, 3)
		return 3
	}

	Register(L, table, Map{
		name: f,
	})
}
```
And change `Init()` with this:
```
	Register(L, "", Map{
		"pairs": ProxyPairs,
		"type":  ProxyType,
	})
	// 'ipairs' needs a special case for performance reasons.
	RegProxyIpairs(L, "", "ipairs")
```

Comments?

**Comment by huangwei1024** [comment]
what is _"all cases"_ mean?

example:
```
func Init() {
  L.GetGlobal("ipairs")
  L.SetGlobal("lua_ipairs")
  
  luar.Register(L, "luar", luar.Map{})
  ...
}

func ProxyIpairs(L *lua.State) int {
	L.CheckType(1, lua.LUA_TTABLE)
        L.GetGlobal("lua_ipairs")
        if L.IsFunction(-1) {
                L.Call(1, 3)
        } else {
              L.PushGoFunction(ipairsAux)
	       L.PushValue(1)
	       L.PushInteger(0)
	}
	return 3
}
```

**Comment by huangwei1024** [comment]
yeah, almost that means

**Comment by Ambrevar** [comment]
Your solution is not reliable as `lua_ipairs` can be overriden anytime, unbeknownst to the user.

The idiomatic way to handle those cases in Lua is to use Lua references, like I did above.

**Comment by huangwei1024** [comment]
yeah, I known example code not reliable, just show when user called `Init` or nothing.

**Comment by Ambrevar** [comment]
Alright, I'll merge my solution then.

**Comment by huangwei1024** [comment]
I think its tradeoff solution better than previous, tks
